# Site
name: 'Sidmach Analytics'
description: 'Sidmach Analytics is the place where data meets purpose.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'Data-science-grp@sidmach.com'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Wale:
      name:           Wale
      site:           https://CaduceusInc.github.io
      avatar:         /assets/images/avatar3.jpg
      bio:            "Hi, I am Wale, a machine learning engineer and data scientist at Sidmach Technologies. I love building intelligent tools and helping others do the same."
      email:          ojopakunle@sidmach.com
      twitter:        https://twitter.com/__Opa_


    Daniel:
      name:           Daniel
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar2.jpg
      bio:            "Software developer and data engineer at Sidmach Analytics. I love to explore new ideas and change lives while at it."
      email:          doadaji@sidmach.com
      twitter:        https://twitter.com/wowthemesnet

    Gafar:
      name:           Gafar
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar2.jpg
      bio:            "Full-stack software developer and data scientist at Sidmach Analytics. I love bringing my ideas to life!"
      email:          aaabodunrin@sidmach.com
      twitter:        https://twitter.com/wowthemesnet

    Mumin:
      name:           Mumin
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar2.jpg
      bio:            "Software developer and data scientist at Sidmach Analytics love to explore new ideas and write on my morning coffee!"
      email:          ashehu@sidmach.com
      twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Wale
      avatar: /assets/images/avatar3.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]